#ifndef CONSTANT_H
#define CONSTANT_H

#define FONT_WIDTH 9
#define FONT_HEIGHT 10
#define BYTE_PER_PIXEL 4
#define FILE_HEADER_SIZE 14
#define INFO_HEADER_SIZE 40

enum TEXT_ALIGN {LEFT, CENTER, RIGHT};
enum OBJ_TYPE {NOTHING, MY_POINT, LINE, POLYGON, CIRCLE, CURVE, TEXT};

#endif